# Generated by Django 2.1 on 2020-08-05 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20200805_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 5, 17, 25, 5, 773041)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='listing',
            field=models.CharField(max_length=200),
        ),
    ]
