# Generated by Django 2.1 on 2020-08-05 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20200805_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='listing_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 5, 17, 27, 42, 443190)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='listing',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
