# Generated by Django 2.1 on 2020-03-09 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200309_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 9, 20, 41, 47, 385904)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='save',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year_built',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 9, 20, 41, 47, 385904), null=True),
        ),
    ]
