# Generated by Django 2.1 on 2020-03-09 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200309_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='save',
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 9, 20, 42, 35, 610386)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year_built',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 9, 20, 42, 35, 610386), null=True),
        ),
    ]
