# Generated by Django 2.1 on 2020-08-06 05:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200805_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm_Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 6, 11, 41, 4, 587124))),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 6, 11, 41, 4, 583130)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year_built',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 6, 11, 41, 4, 583130), null=True),
        ),
        migrations.AddField(
            model_name='confirm_sales',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.Listing'),
        ),
    ]
