# Generated by Django 2.1 on 2020-08-06 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20200806_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm_sales',
            name='sale_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 6, 12, 11, 8, 953709)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 6, 12, 11, 8, 951712)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('sold', 'sold')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year_built',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 6, 12, 11, 8, 951712), null=True),
        ),
    ]
