# Generated by Django 2.1 on 2020-03-09 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20200309_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 9, 20, 43, 32, 438867)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year_built',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 9, 20, 43, 32, 438867), null=True),
        ),
    ]
