# Generated by Django 2.1 on 2020-04-09 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20200325_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 9, 12, 44, 11, 825874)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year_built',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 9, 12, 44, 11, 825874), null=True),
        ),
    ]
