# Generated by Django 2.1 on 2020-04-09 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20200409_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 9, 19, 40, 36, 744191)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year_built',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 9, 19, 40, 36, 744191), null=True),
        ),
    ]
