# Generated by Django 2.1 on 2020-04-16 15:58

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0022_auto_20200416_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_saved',
        ),
        migrations.AddField(
            model_name='listing',
            name='is_saved',
            field=models.ManyToManyField(blank=True, related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 16, 21, 43, 4, 790848)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year_built',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 16, 21, 43, 4, 790848), null=True),
        ),
    ]
