# Generated by Django 2.1 on 2020-04-17 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_auto_20200416_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_saved',
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 6, 55, 4, 310070)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year_built',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 6, 55, 4, 310070), null=True),
        ),
    ]
