# Generated by Django 2.1 on 2020-04-18 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_auto_20200417_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='energy_features',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='property_type',
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 18, 18, 47, 30, 768016)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year_built',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 18, 18, 47, 30, 768016), null=True),
        ),
    ]
