# Generated by Django 2.1 on 2020-05-04 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_auto_20200504_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('garage', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('total_rooms', models.IntegerField(blank=True, null=True)),
                ('sqft', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('year_built', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 4, 19, 25, 17, 299424), null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='address',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='description',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='district',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sqft',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='total_rooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='year_built',
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 4, 19, 25, 17, 296439)),
        ),
        migrations.AddField(
            model_name='listingfeatures',
            name='features',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='listings.Listing'),
        ),
        migrations.AddField(
            model_name='listingdetails',
            name='details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='listings.Listing'),
        ),
    ]
