# Generated by Django 2.1 on 2020-05-04 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_auto_20200504_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingdetails',
            name='description',
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 4, 19, 33, 0, 350975)),
        ),
        migrations.AlterField(
            model_name='listingfeatures',
            name='year_built',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 4, 19, 33, 0, 353004), null=True),
        ),
    ]
