# Generated by Django 2.1 on 2020-05-04 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_auto_20200504_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingdetails',
            name='details',
        ),
        migrations.RemoveField(
            model_name='listingfeatures',
            name='features',
        ),
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='garage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='year_built',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 4, 19, 54, 37, 323350), null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 4, 19, 54, 37, 324348)),
        ),
        migrations.DeleteModel(
            name='ListingDetails',
        ),
        migrations.DeleteModel(
            name='ListingFeatures',
        ),
    ]
