# Generated by Django 2.1 on 2020-06-03 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_auto_20200504_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 3, 10, 4, 44, 644488, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year_built',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 3, 10, 4, 44, 644488, tzinfo=utc), null=True),
        ),
    ]
