# Generated by Django 2.1 on 2020-04-15 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0007_auto_20200415_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 15, 18, 13, 41, 49491)),
        ),
    ]
