# Generated by Django 2.1 on 2020-06-03 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0016_auto_20200418_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 3, 10, 4, 44, 621735, tzinfo=utc)),
        ),
    ]
