# Generated by Django 2.1 on 2020-07-05 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0017_auto_20200603_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 5, 6, 45, 20, 855958)),
        ),
    ]
