# Generated by Django 2.1 on 2020-04-09 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spam_filtering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, max_length=1000)),
                ('type', models.IntegerField(choices=[(1, 'spam'), (2, 'ham')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.Contact')),
            ],
        ),
    ]
