# Generated by Django 2.1 on 2020-07-05 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam_filtering',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 12, 41, 42, 725462), null=True),
        ),
    ]
