# Generated by Django 2.1 on 2020-04-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam_filtering',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='spam_filtering',
            name='user_id',
            field=models.IntegerField(blank=True),
        ),
    ]
