# Generated by Django 2.1 on 2020-08-03 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_filter', '0002_auto_20200705_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam_filtering',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 19, 59, 2, 850281), null=True),
        ),
    ]
