# Generated by Django 2.1 on 2020-04-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_filter', '0002_auto_20200409_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='spam_filtering',
            name='listing_id',
            field=models.IntegerField(null=True),
        ),
    ]
