# Generated by Django 2.1 on 2020-04-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_filter', '0003_spam_filtering_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spam_filtering',
            name='user_firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spam_filtering',
            name='user_lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
