# Generated by Django 2.1 on 2020-08-05 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_filter', '0003_auto_20200803_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam_filtering',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 17, 12, 21, 281575), null=True),
        ),
    ]
