# Generated by Django 2.1 on 2020-04-15 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spam_filter', '0004_auto_20200414_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='spam_filtering',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
