# Generated by Django 2.1 on 2020-04-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spam_filter', '0005_spam_filtering_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spam_filtering',
            name='likes',
        ),
    ]
