# Generated by Django 2.1 on 2020-04-16 15:30

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spam_filter', '0008_auto_20200416_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='spam_filtering',
            name='likes',
        ),
        migrations.AddField(
            model_name='spam_filtering',
            name='likes',
            field=models.IntegerField(blank=True, default=1, verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spam_filtering',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 21, 14, 34, 120129), null=True),
        ),
        migrations.AddField(
            model_name='commentlikes',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spam_filter.Spam_filtering'),
        ),
        migrations.AddField(
            model_name='commentlikes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
