# Generated by Django 2.1 on 2020-04-16 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_filter', '0009_auto_20200416_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlikes',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentlikes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='spam_filtering',
            name='likes',
        ),
        migrations.AlterField(
            model_name='spam_filtering',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 21, 31, 34, 757587), null=True),
        ),
        migrations.DeleteModel(
            name='CommentLikes',
        ),
    ]
