# Generated by Django 2.1 on 2020-04-16 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_filter', '0010_auto_20200416_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam_filtering',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 21, 43, 4, 796863), null=True),
        ),
    ]
