# Generated by Django 2.1 on 2020-04-17 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_filter', '0012_auto_20200417_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam_filtering',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 17, 14, 52, 383521), null=True),
        ),
    ]
