# Generated by Django 2.1 on 2020-06-03 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spam_filter', '0014_auto_20200418_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam_filtering',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 10, 4, 44, 691670, tzinfo=utc), null=True),
        ),
    ]
