# Generated by Django 2.1 on 2020-07-05 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_filter', '0015_auto_20200603_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam_filtering',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 6, 45, 20, 864217), null=True),
        ),
    ]
